import { EmployeeRole } from '../enums/employee.enum'
import { PermissionKey } from '../enums/permission-enum'

export const mockUpRoleList = [
  {
    name: 'หัวหน้า',
    type: EmployeeRole.CEO,
    permissions: [
      {
        name: 'EMPLOYEE',
        key: PermissionKey.EMPLOYEE,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'BOOKING',
        key: PermissionKey.BOOKING,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'CALENDAR',
        key: PermissionKey.CALENDAR,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'GURANTEE',
        key: PermissionKey.GURANTEE,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'PRODUCT',
        key: PermissionKey.PRODUCT,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'SALARY',
        key: PermissionKey.SALARY,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'BIN',
        key: PermissionKey.BIN,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'EXPENSE',
        key: PermissionKey.EXPENSE,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'FINANCE',
        key: PermissionKey.FINANCE,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'SETTING',
        key: PermissionKey.SETTING,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'COMPANY',
        key: PermissionKey.COMPANY,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'ROLE',
        key: PermissionKey.ROLE,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
    ],
  },
  {
    name: 'ผู้ดูแลระบบ',
    type: EmployeeRole.AMIN,
    permissions: [
      {
        name: 'EMPLOYEE',
        key: PermissionKey.EMPLOYEE,
        hasView: true,
        hasEdit: true,
        hasDelete: false,
      },
      {
        name: 'BOOKING',
        key: PermissionKey.BOOKING,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'CALENDAR',
        key: PermissionKey.CALENDAR,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'GURANTEE',
        key: PermissionKey.GURANTEE,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'PRODUCT',
        key: PermissionKey.PRODUCT,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'SALARY',
        key: PermissionKey.SALARY,
        hasView: true,
        hasEdit: true,
        hasDelete: false,
      },
      {
        name: 'BIN',
        key: PermissionKey.BIN,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'EXPENSE',
        key: PermissionKey.EXPENSE,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'FINANCE',
        key: PermissionKey.FINANCE,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'SETTING',
        key: PermissionKey.SETTING,
        hasView: true,
        hasEdit: true,
        hasDelete: false,
      },
      {
        name: 'COMPANY',
        key: PermissionKey.COMPANY,
        hasView: true,
        hasEdit: true,
        hasDelete: false,
      },
      {
        name: 'ROLE',
        key: PermissionKey.ROLE,
        hasView: true,
        hasEdit: true,
        hasDelete: false,
      },
    ],
  },
  {
    name: 'ช่างล้างรถ',
    type: EmployeeRole.WASHTECNICIAN,
    permissions: [
      {
        name: 'EMPLOYEE',
        key: PermissionKey.EMPLOYEE,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'BOOKING',
        key: PermissionKey.BOOKING,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'CALENDAR',
        key: PermissionKey.CALENDAR,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'GURANTEE',
        key: PermissionKey.GURANTEE,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'PRODUCT',
        key: PermissionKey.PRODUCT,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'SALARY',
        key: PermissionKey.SALARY,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'BIN',
        key: PermissionKey.BIN,
        hasView: false,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'EXPENSE',
        key: PermissionKey.EXPENSE,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'FINANCE',
        key: PermissionKey.FINANCE,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'SETTING',
        key: PermissionKey.SETTING,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'COMPANY',
        key: PermissionKey.COMPANY,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'ROLE',
        key: PermissionKey.ROLE,
        hasView: false,
        hasEdit: false,
        hasDelete: false,
      },
    ],
  },
  {
    name: 'ช่างพ่นสี',
    type: EmployeeRole.SPRAYER,
    permissions: [
      {
        name: 'EMPLOYEE',
        key: PermissionKey.EMPLOYEE,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'BOOKING',
        key: PermissionKey.BOOKING,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'CALENDAR',
        key: PermissionKey.CALENDAR,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'GURANTEE',
        key: PermissionKey.GURANTEE,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'PRODUCT',
        key: PermissionKey.PRODUCT,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'SALARY',
        key: PermissionKey.SALARY,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'BIN',
        key: PermissionKey.BIN,
        hasView: false,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'EXPENSE',
        key: PermissionKey.EXPENSE,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'FINANCE',
        key: PermissionKey.FINANCE,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'SETTING',
        key: PermissionKey.SETTING,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'COMPANY',
        key: PermissionKey.COMPANY,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'ROLE',
        key: PermissionKey.ROLE,
        hasView: false,
        hasEdit: false,
        hasDelete: false,
      },
    ],
  },
]
