import { DeleteStatus } from '../enums/delete-status.enum'
import { PermissionKey } from '../enums/permission-enum'

export const mockUpPermissions = [
  {
    name: 'EMPLOYEE',
    key: PermissionKey.EMPLOYEE,
    hasView: true,
    hasEdit: false,
    hasDelete: false,
  },
  {
    name: 'BOOKING',
    key: PermissionKey.BOOKING,
    hasView: true,
    hasEdit: false,
    hasDelete: false,
  },
  {
    name: 'CALENDAR',
    key: PermissionKey.CALENDAR,
    hasView: true,
    hasEdit: false,
    hasDelete: false,
  },
  {
    name: 'GURANTEE',
    key: PermissionKey.GUARANTEE,
    hasView: true,
    hasEdit: false,
    hasDelete: false,
  },
  {
    name: 'PRODUCT',
    key: PermissionKey.PRODUCT,
    hasView: true,
    hasEdit: false,
    hasDelete: false,
  },
  {
    name: 'EXPENSE',
    key: PermissionKey.EXPENSE,
    hasView: true,
    hasEdit: false,
    hasDelete: false,
  },
  {
    name: 'SALARY',
    key: PermissionKey.SALARY,
    hasView: true,
    hasEdit: false,
    hasDelete: false,
  },
  {
    name: 'FINANCE',
    key: PermissionKey.FINANCE,
    hasView: true,
    hasEdit: false,
    hasDelete: false,
  },
  {
    name: 'BIN',
    key: PermissionKey.BIN,
    hasView: false,
    hasEdit: false,
    hasDelete: false,
  },
  {
    name: 'SETTING',
    key: PermissionKey.SETTING,
    hasView: true,
    hasEdit: false,
    hasDelete: false,
  },
  {
    name: 'COMPANY',
    key: PermissionKey.COMPANY,
    hasView: true,
    hasEdit: false,
    hasDelete: false,
  },
  {
    name: 'ROLE',
    key: PermissionKey.ROLE,
    hasView: false,
    hasEdit: false,
    hasDelete: false,
  },
  {
    name: 'TYPEPRODUCT',
    key: PermissionKey.TYPEPRODUCT,
    hasView: false,
    hasEdit: false,
    hasDelete: false,
  },
]

export const mockUpRoleList = [
  {
    name: 'หัวหน้า',
    type: 'CEO',
    permissions: [
      {
        name: 'EMPLOYEE',
        key: PermissionKey.EMPLOYEE,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'BOOKING',
        key: PermissionKey.BOOKING,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'CALENDAR',
        key: PermissionKey.CALENDAR,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'GUARANTEE',
        key: PermissionKey.GUARANTEE,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'PRODUCT',
        key: PermissionKey.PRODUCT,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'EXPENSE',
        key: PermissionKey.EXPENSE,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'SALARY',
        key: PermissionKey.SALARY,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'FINANCE',
        key: PermissionKey.FINANCE,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'BIN',
        key: PermissionKey.BIN,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'SETTING',
        key: PermissionKey.SETTING,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'COMPANY',
        key: PermissionKey.COMPANY,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'ROLE',
        key: PermissionKey.ROLE,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'TYPEPRODUCT',
        key: PermissionKey.TYPEPRODUCT,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
    ],
    delete: DeleteStatus.ISNOTDELETE,
  },
  {
    name: 'ผู้ดูแลระบบ',
    type: 'ADMIN',
    permissions: [
      {
        name: 'EMPLOYEE',
        key: PermissionKey.EMPLOYEE,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'BOOKING',
        key: PermissionKey.BOOKING,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'CALENDAR',
        key: PermissionKey.CALENDAR,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'GURANTEE',
        key: PermissionKey.GUARANTEE,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'PRODUCT',
        key: PermissionKey.PRODUCT,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'EXPENSE',
        key: PermissionKey.EXPENSE,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'SALARY',
        key: PermissionKey.SALARY,
        hasView: true,
        hasEdit: true,
        hasDelete: false,
      },
      {
        name: 'FINANCE',
        key: PermissionKey.FINANCE,
        hasView: true,
        hasEdit: true,
        hasDelete: true,
      },
      {
        name: 'BIN',
        key: PermissionKey.BIN,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'SETTING',
        key: PermissionKey.SETTING,
        hasView: true,
        hasEdit: true,
        hasDelete: false,
      },
      {
        name: 'COMPANY',
        key: PermissionKey.COMPANY,
        hasView: true,
        hasEdit: true,
        hasDelete: false,
      },
      {
        name: 'ROLE',
        key: PermissionKey.ROLE,
        hasView: true,
        hasEdit: true,
        hasDelete: false,
      },
      {
        name: 'TYPEPRODUCT',
        key: PermissionKey.TYPEPRODUCT,
        hasView: true,
        hasEdit: true,
        hasDelete: false,
      },
    ],
    delete: DeleteStatus.ISNOTDELETE,
  },
  {
    name: 'พนักงาน',
    type: 'EMPLOYEE',
    permissions: [
      {
        name: 'EMPLOYEE',
        key: PermissionKey.EMPLOYEE,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'BOOKING',
        key: PermissionKey.BOOKING,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'CALENDAR',
        key: PermissionKey.CALENDAR,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'GURANTEE',
        key: PermissionKey.GUARANTEE,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'PRODUCT',
        key: PermissionKey.PRODUCT,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'EXPENSE',
        key: PermissionKey.EXPENSE,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'SALARY',
        key: PermissionKey.SALARY,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'FINANCE',
        key: PermissionKey.FINANCE,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'BIN',
        key: PermissionKey.BIN,
        hasView: false,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'SETTING',
        key: PermissionKey.SETTING,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'COMPANY',
        key: PermissionKey.COMPANY,
        hasView: true,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'ROLE',
        key: PermissionKey.ROLE,
        hasView: false,
        hasEdit: false,
        hasDelete: false,
      },
      {
        name: 'TYPEPRODUCT',
        key: PermissionKey.TYPEPRODUCT,
        hasView: false,
        hasEdit: false,
        hasDelete: false,
      },
    ],
    delete: DeleteStatus.ISNOTDELETE,
  },
]
