export enum PermissionKey {
  EMPLOYEE = 0,
  BOOKING = 1,
  CALENDAR = 2,
  GURANTEE = 3,
  PRODUCT = 4,
  EXPENSE = 5,
  SALARY = 6,
  FINANCE = 7,
  BIN = 8,
  SETTING = 9,
  COMPANY = 10,
  ROLE = 11,
  TYPEPRODUCT = 12,
}
