name: Deploy NestJS to Plesk

on:
  push:
    branches:
      - master   # หรือ branch ที่ต้องการ deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22   # เลือกเวอร์ชันที่ใช้จริงใน Plesk ด้วย

      # 3) Install dependencies (Yarn)
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 4) Build NestJS
      - name: Build NestJS
        run: yarn build

      # 5) Deploy dist + package.json + yarn.lock ไป Plesk
      - name: Deploy to Plesk via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /api.gunprotections.com/dist/

      # 6) อาจต้อง upload package.json + yarn.lock ด้วย (ถ้า Plesk จะ run yarn install ที่ server)
      - name: Upload package.json & yarn.lock
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /api.gunprotections.com/
          exclude: |
            **/*
            !package.json
            !yarn.lock
