name: Deploy NestJS to Plesk (Node.js Extension)

on:
  push:
    branches: [ main ]

concurrency:
  group: deploy-nestjs-plesk
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies (prod only)
        run: npm ci --omit=dev

      - name: Build NestJS
        run: npm run build

      # สร้างโฟลเดอร์ deploy ที่มีเฉพาะของจำเป็น
      - name: Prepare deploy folder
        run: |
          rm -rf deploy
          mkdir -p deploy
          cp -r dist deploy/dist
          cp package.json package-lock.json deploy/
          cp -r node_modules deploy/node_modules

      - name: Deploy to Plesk via FTP/FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # ถ้าใช้ FTPS ให้เปิดบรรทัดนี้
          protocol: ftps
          local-dir: deploy
          server-dir: httpdocs/nestjs-app
          dangerous-clean-slate: true
          exclude: |
            **/.git*
            **/.DS_Store
          timeout: 600000
